<footer class="py-3 my-4 border-top">
  <div class="container">
    <div class="d-flex flex-wrap justify-content-center justify-content-md-between align-items-center">
      <p class="col-md-4 mb-0 text-body-secondary">© 2024 Company, Inc</p>

      <a href="/" class="col-md-4 d-none d-md-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <span>BRAND</span>
      </a>

      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
      </ul>
    </div>
  </div>
</footer>